### ISSUE TITLE
Milestone 8: Feeds

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/exchangebuddy#3]
> **Milestone 8:** We want some feeds! BUT remember to put thought into this. Nuisance feeds will not only earn you no credit but may incur penalization!

I think what they mean by this would be the "Share" button for the user to publish a post onto his timeline.

What I suggest we can use the Share button for would be:
- [ ] Share the website (from footer)
- [ ] Share the university wiki page
  - This would mean that we have to allow non-users to view the wiki tab as a standalone and prompt them to sign up.
- [ ] Share a Facebook event from the Events tab

**Comment by irvinlim** [comment]
https://developers.facebook.com/docs/sharing/reference/feed-dialog
