### ISSUE TITLE
Milestone 9: Likes

### ISSUE THREAD

**Issue by irvinlim** [irvinlim/exchangebuddy#4]
> **Milestone 9:** Your application should include the Like button for your users to click on. Convince us why you think that is the best place you should place the button.

Suggestions:
- [ ] Place in the footer
- [ ] Like the whole wiki page/university page
- [ ] Like individual cards on the wiki?

**Comment by irvinlim** [comment]
https://developers.facebook.com/docs/plugins/like-button
